# Generated by Django 3.0.4 on 2020-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc1',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
